export const catsStyles = {
  container: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    width: "100vw",
  },
  viewerContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: "500px",
    minWidth: "500px",
    aspectRatio: "1/1",
    height: "80%",
    border: "1px solid white",
  },
  viewerTitle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "15%",
    width: "100%",
  },
  viewerImage: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "75%",
    width: "100%",
  },
  image: {
    height: "100%",
    width: "100%",
  },
  viewerButtons: {
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    height: "15%",
    width: "100%",
    backgroundColor: "green",
  },
  favoriteContainer: {
    marginTop: "30px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px",
    height: "80px",
    width: "90%",
    border: "1px solid white",
    overflowY: "hidden",
    overflowX: "auto",
  },
  favoriteCard: {
    maxWidth: "50px",
    maxHeight: "50px",
    aspectRatio: "1/1",
  },
};
